theme: jekyll-theme-minimal
logo: /assets/img/profile.jpg
description: >-
  Welcome to my website ! 
author: Valerii Vasyliev
email: info@gratta.pro
title: CV
description: Valerii Vasyliev's CV

google_analytics: UA-6622139-13

# social links
twitter_username: valeriivasyliev
github_username: valeriivasyliev
linkedin_username: vvasyliev

# project links:
twitter: https://twitter.com/valeriiVasiliev

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
